name: Validate with hassfest

on:
  push:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"
        - name: HACS Action
          uses: "hacs/action@main"
          with:
            category: "integration"
